#!/usr/bin/env bash
# # output subdomain, record type and destination

display_domain_info(){
        res=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | grep "$1")
        echo "$2 $res" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6 }'
}

if [ "$#" == 1 ]; then
        display_domain_info "$1" "www"
        display_domain_info "$1" "lb-01"
        display_domain_info "$1" "web-01"
        display_domain_info "$1" "web-02"
elif [ "$#" == 2 ]; then
        display_domain_info "$1" "$2"
fi
