#!/usr/bin/env bash
# copies a file from client to server

file_path="$1"
ip="$2"
user="$3"
key_path="$4"

if [ "$#" -lt 3 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit
fi

if [ "$#" -ge 4 ]
then
        scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" "$user"@"$ip":~/
else
        scp -o StrictHostKeyChecking=no "$file_path" "$user"@"$ip":~/
fi
