#!/usr/bin/env bash
# Transfers a file from client to remote server via scp

if [$# -lt 3]
then
		echo "Usage: 0-transfer_file PATH_TO_FILE IO USERNAME PATH_TO_SSH_KEY"
		exit 1
fi

scp -o StrictHostKetChecking=no -i "$4" "$1" "$3@$2:~/"
