#!/usr/bin/env bash
# installs nginx and displays hello world

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
sudo service nginx restart
