#!/usr/bin/env bash
# installs nginx and displays hello world

sudo apt-get -y update
sudo apt-get install nginx -y
ufw allow 80
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
