#!/usr/bin/env bash
# error 404 custom page

REDIRECTION="\
    location /redirect_me {\n\
        return 301 https://www.hamidas-portfolio.webflow.io;\n\
    }\n"

CONFIG_FILE="/etc/nginx/sites-available/default"

ERRORFILE="/var/www/html/error_404.html"
MESSAGE="Ceci n'est pas une page"
ERROR_REDIRECTION="\
        error_page 404 /error_404.html;\
        location = /404error.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a $REDIRECTION" "$CONFIG_FILE"

echo "$MESSAGE" > "$ERRORFILE"
sed -i "/server_name _;/a $ERROR_REDIRECTION" "$CONFIG_FILE"

service nginx restart
