#!/usr/bin/env bash
# configuring second server

sudo apt-get update
sudo apt-get install nginx -y

sudo chown -R "$USER":"sudo" /var/www/html
echo "Hello World!" > /var/www/html/index.html
CONFIG_FILE="/etc/nginx/sites-available/default"
REDIRECT="\
	location /redirect {\n\
		return 301 https://hamidas-portfolio.webflow.io/;\n\
	}\n"

sudo sed -i "/server_name _;/a\ $REDIRECT" "$CONFIG_FILE"

MESSAGE="Ceci n'est pas une page"
ERROR_FILE="/var/www/html/error_404.html"

echo "$MESSAGE" > "$ERROR_FILE"
ERROR_PAGE="\terror_page 404 /error_404.html;"
REDIRECTION="\
	location /error_404.html {\n\
		root /var/www/html/;\n\
		internal;\n\
	}"

sudo sed -i "/server_name _;/a\ $REDIRECTION" "$CONFIG_FILE"
sudo sed -i "/server_name _;/a\ $ERROR_PAGE" "$CONFIG_FILE"

HEADER="\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "/server_name _;/a\ $HEADER" "$CONFIG_FILE"

sudo service nginx restart
