#!/usr/bin/env bash
# error 404 custom page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www

REDIRECTION="\
    location /redirect_me {\n\
        return 301 https://www.hamidas-portfolio.webflow.io;\n\
    }\n"

CONFIG_FILE="/etc/nginx/sites-available/default"

ERRORFILE="/var/www/html/error_404.html"
MESSAGE="Ceci n'est pas une page"
ERROR_REDIRECTION="\
        error_page 404 /error_404.html;\
        location = /404error.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"


echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/a $REDIRECTION" "$CONFIG_FILE"

echo "$MESSAGE" > "$ERRORFILE"
sudo sed -i "/server_name _;/a $ERROR_REDIRECTION" "$CONFIG_FILE"

sudo sed -i "/server_name _;/a \n\tadd_header X-Served-By \"$(hostname)\";" "$CONFIG_FILE"

sudo service nginx restart
