#!/usr/bin/env bash
# Install and configure HAproxy on your server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 103274-web-01 54.161.255.250:80 check\n\tserver 103274-web-02 54.236.33.119:80 check\n' /etc/haproxy/haproxy.cfg

service haproxy restart
