#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

password="$1"
formatted_date=$(date +'%d-%m-%Y')
sudo mysqldump -u root -p "$password" --all-databases > backup.sql
tar -czvf "$formatted_date".tar.gz backup.sql
