#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

formatted_date=$(date + %d-%m-%Y)
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$formatted_date".tar.gz backup.sql
