#!/usr/bin/env bash
#This script displays from 1 to 10 and:
# - displays bad luck for the 4th loop iteration
# - displays good luck for the 8th loop iteration
# - displays Best School for the other iterations

i=0

while [ "$i" -le 9 ]
do
    if [ "$i" -eq 3 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "goodluck"
    else
        echo "Best School"
    fi
    ((i++))
done
