#!/usr/bin/env bash
#This script displays from 1 to 10 

i=0

while [ "$i" -le 9 ]
do
    if [ "$i" -eq 3 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "goodluck"
    else
        echo "Best School"
    fi
    ((i++))
done
