#!/usr/bin/env bash
#This script gives you information about the school file.

SCHOOL="school"

if [ -e "$SCHOOL" ]
then
    echo "school file exists"
    if [ -s "$SCHOOL" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$SCHOOL" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi