#!/usr/bin/env bash
# configures the firewall to block all incoming traffic except for some ports
apt-get install ufw
sed -i 's/IPV6=no/IPV6=yes/g' /etc/default/ufw
ufw disable
ufw enable 
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
